server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql:///mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 6125
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
  redis:
    client-name: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  security:
    user:
      name: yxyl
      password: 6125
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9200 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead:   #JWT负载中拿到开头
